cli/src/export.rs

Add nothing format to check exact performance of compiling a document

Feat(cli): add nothing format

---

tsconfig.json

A root tsconfig would help ide discover all typescript sub packages/projects.

Chore: add root tsconfig

---

Dockerfile

To allow vergen scanning git information.

Fix(ci): add entire repository folder

---

.github/workflows/docker.yaml

This is required by vergen build script.

Fix(ci): let docker context capture .git

---

.gitattributes

This would help lately typst development

Feat: set linguist language of typst source files

---

packages/renderer/src/artifact.rs
packages/renderer/src/artifact_ir.rs
packages/renderer/src/lib.rs
packages/renderer/src/session.rs

dev(pkg::renderer) clean up error handling

---

core/src/artifact/geom.rs
packages/renderer/src/artifact.rs

fix(core): bad serialization of PathItem

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/main.rs

implement https://github.com/Myriad-Dreamin/typst.ts/issues/81

feat(cli): use human-panic

---

exporter/svg/src/lib.rs
exporter/svg/src/render/flat.rs
exporter/svg/src/render/incremental.rs

- 之前写了个bug。。查找的顺序弄反了，应该是在新的glyph set里面做filter.
- 此外给 glyph 的 `<g>` 加了一个 id, 方便前端用

fix(svg): fix incremental glyph

---

exporter/svg/src/lib.rs
exporter/svg/src/render/incremental.rs

chore(svg): adjust defs structure

---

exporter/svg/src/flat_incr_vector/codegen.rs
exporter/svg/src/flat_incr_vector/mod.rs
exporter/svg/src/flat_incr_vector/vm.rs
exporter/svg/src/flat_vector/codegen.rs
exporter/svg/src/lib.rs
exporter/svg/src/render/flat.rs
exporter/svg/src/render/incremental.rs
exporter/svg/src/vector/ir.rs

work with [preview#42](https://github.com/Enter-tainer/typst-preview-vscode/pull/42)

dev: incremental svg exporter vm with naive reuse decision

---

core/src/hash.rs

dev(core): replace typst_affinite_hash

---

compiler/src/service/diag.rs

+ upstream: https://github.com/typst/typst/commit/ef1bf742f6b73e60a8adb40281140314dc3e7ff4

dev(compiler): emit plain text if out isn't a TTY

---

compiler/src/world.rs

fix(compiler): reset today for each compilation

---

compiler/src/vfs/mod.rs

+ upstream https://github.com/typst/typst/commit/6db4c39cd98631dd621d05120638d1b3e5f73ce0

dev(compiler): ignore utf-8 bom

---

compiler/src/service/diag.rs
compiler/src/service/driver.rs

+ upstream https://github.com/typst/typst/commit/48c25f4da01aa5cbd5e49145f591c85b676e8a54

dev(compiler): display compile time in status msg

---

compiler/src/vfs/browser.rs
compiler/src/vfs/cached.rs
compiler/src/vfs/mod.rs
compiler/src/vfs/overlay.rs
compiler/src/vfs/trace.rs

+ to correct cache behavior
+ merge replace and read source impl
+ fix CompilerWorld::resolve_with

dev(compiler): add overlay access model

---

core/src/vector/flat_ir.rs
core/src/vector/flat_vm.rs
exporter/svg/src/backend/mod.rs

+ by `render_diff_item_ref_at`

dev(core): replace `render_diff_reuse_item`

---

compiler/src/service/driver.rs

Just a mitigation, need investigation

fix(compiler): ignore inotify events from output

---

core/src/exporter.rs
core/src/lib.rs

+ likely unnecessary in new vesrion of rust

dev(core): remove mark_transformer_lambda

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/compile.rs
cli/src/export.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/query.rs
cli/src/query_repl.rs
compiler/src/service/driver.rs
compiler/src/service/mod.rs
compiler/src/service/query.rs

* dev: repl backbone
* refactor query api
* dev: use typst autocompletion
* auto completing pair
---------

feat: interactive query command (#288)

---

Cargo.toml

build: fix dep of unpublish packages

---

Cargo.lock
Cargo.toml
package.json
packages/compiler/package.json
packages/hexo-renderer-typst/package.json
packages/renderer/package.json
packages/typst.angular/projects/typst.angular/package.json
packages/typst.react/package.json
packages/typst.ts/package.json
packages/typst.ts/src/renderer.ts

fix issue that cannot create an empty session

build: update to rc4

---

compiler/src/vfs/mod.rs

fix https://github.com/Enter-tainer/typst-preview/issues/151

fix: vfs panic when file not found

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/lib.rs
cli/src/main.rs
cli/src/manual.rs

+ https://github.com/typst/typst/pull/582

feat(cli): manual generation

---

projects/rehype-typst/equation.typ
projects/rehype-typst/index.js
projects/rehype-typst/lib/index.js
projects/rehype-typst/package.json
projects/rehype-typst/test.js
projects/rehype-typst/turbo.json
yarn.lock

feat: add rehype-typst

---

compiler/src/package/http.rs
fuzzers/corpora/package/self-200-package.typ
fuzzers/corpora/package/self-404-package.typ

Reverts Myriad-Dreamin/typst.ts#465

revert: "fix(compiler): correctly detect not found packages"

---

packages/typst.ts/examples/all-in-one-lite.html
packages/typst.ts/src/contrib/snippet.mts
packages/typst.ts/src/renderer.mts
packages/typst.ts/src/utils.mts

feat: use random main file path for svg by mainContent

---

compiler/src/font/system.rs
compiler/src/lib.rs
compiler/src/service/compile.rs
compiler/src/service/driver.rs
compiler/src/service/mod.rs
compiler/src/service/watch.rs
compiler/src/vfs/mod.rs
compiler/src/vfs/notify.rs
compiler/src/world.rs
core/src/lib.rs
crates/reflexo/src/vector/ir/color.rs
packages/typst.node/src/compiler/boxed.rs
server/dev/src/http.rs

fix the bug triggered by operations:
```bash
// compile: ok
remove dep.typ
ctrl+s
// compile: not found error
git restore dep.typ
ctrl+s
// compile: not found error
```

fix: restore from "file not found" error after restoring deleted file 

---

Cargo.lock

build: bump typst to v0.11.1

---

projects/rehype-typst/equation.typ
projects/rehype-typst/lib/index.js

fix(rehype-typst): inline math not rendering

---

packages/enhanced-typst-svg/package.json
packages/enhanced-typst-svg/src/index.ts
packages/enhanced-typst-svg/src/style.css

Also wrapper the code with an anonymous function to avoid global scope pollution.

feat: add style.css to enhanced-typst-svg bundle

---

packages/typst.ts/src/contrib/snippet.mts
packages/typst.ts/tests/issue-679.html
projects/rustdoc-typst-demo/.gitignore
projects/rustdoc-typst-demo/Cargo.toml
projects/rustdoc-typst-demo/Makefile.toml
projects/rustdoc-typst-demo/README.md
projects/rustdoc-typst-demo/src/lib.rs
projects/rustdoc-typst-demo/typst-header.html

Fix a race condition that `prepareUse` may be called multiple times.

fix: race condition in snippet lib and add rustdoc-typst-demo

---

packages/typst.vue3/src/Typst.vue

fix: Fix incorrect Typst source code change listener in typst.vue3

---

package.json
scripts/decode-sir.ts
server/dev/src/main.rs

fix: don't compile server when running as subprocess

---

packages/typst.ts/src/compiler.mts
packages/typst.ts/src/contrib/snippet.mts
packages/typst.ts/src/options.init.all.test.mts
packages/typst.ts/vitest.workspace.mjs

fix: wrong typing of compile format
